/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wx.JNI;

public class java_wxpanel {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected java_wxpanel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(java_wxpanel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wxpanel_moduleJNI.delete_java_wxpanel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public java_wxpanel(java_wxframe parent, int id, int x, int y, int width, int height, int style, String name) {
    this(wxpanel_moduleJNI.new_java_wxpanel(java_wxframe.getCPtr(parent), parent, id, x, y, width, height, style, name), true);
  }

}
