/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wx.JNI;

public class java_wxapp {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected java_wxapp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(java_wxapp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wxapp_moduleJNI.delete_java_wxapp(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void java_CallOnInit() {
    wxapp_moduleJNI.java_wxapp_java_CallOnInit(swigCPtr, this);
  }

  public void java_OnRun() {
    wxapp_moduleJNI.java_wxapp_java_OnRun(swigCPtr, this);
  }

  public void java_OnExit() {
    wxapp_moduleJNI.java_wxapp_java_OnExit(swigCPtr, this);
  }

  public java_wxapp() {
    this(wxapp_moduleJNI.new_java_wxapp(), true);
  }

}
