/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wx.JNI;

import java.util.HashMap;
import java.lang.ref.WeakReference;

public class java_wxmenuitem {
  private static HashMap<Long, WeakReference<java_wxmenuitem>> instances 
                        = new HashMap<Long, WeakReference<java_wxmenuitem>>();

  private long swigCPtr;
  protected boolean swigCMemOwn;

  public java_wxmenuitem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
    // If derived add it.
    if (getClass() != java_wxmenuitem.class) {
      instances.put(swigCPtr, new WeakReference<java_wxmenuitem>(this));
    }
  }

  // Just the default one
  public static long getCPtr(java_wxmenuitem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  // Helper function that looks up given a pointer and 
  // either creates or returns it
  static java_wxmenuitem createOrLookup(long arg) {
    if (instances.containsKey(arg)) {
      return instances.get(arg).get();
    }
    return new java_wxmenuitem(arg,false);
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
  if (swigCPtr != 0) {
    // Unregister instance
    instances.remove(swigCPtr);
    if (swigCMemOwn) {
      swigCMemOwn = false;
      wxmenubar_moduleJNI.delete_java_wxmenuitem(swigCPtr);
    }
    swigCPtr = 0;
  }
}

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    wxmenubar_moduleJNI.java_wxmenuitem_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    wxmenubar_moduleJNI.java_wxmenuitem_change_ownership(this, swigCPtr, true);
  }

  public java_wxmenuitem(java_wxmenu menu, int id, String name) {
    this(wxmenubar_moduleJNI.new_java_wxmenuitem(java_wxmenu.getCPtr(menu), menu, id, name), true);
    wxmenubar_moduleJNI.java_wxmenuitem_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void OnClick(java_wxmenuitem director) {
    if (getClass() == java_wxmenuitem.class) wxmenubar_moduleJNI.java_wxmenuitem_OnClick(swigCPtr, this, java_wxmenuitem.getCPtr(director), director); else wxmenubar_moduleJNI.java_wxmenuitem_OnClickSwigExplicitjava_wxmenuitem(swigCPtr, this, java_wxmenuitem.getCPtr(director), director);
  }

  public void click_event_occured(SWIGTYPE_p_wxCommandEvent event) {
    wxmenubar_moduleJNI.java_wxmenuitem_click_event_occured(swigCPtr, this, SWIGTYPE_p_wxCommandEvent.getCPtr(event));
  }

}
