/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wx.JNI;

public class java_wxmenubar {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected java_wxmenubar(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(java_wxmenubar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wxmenubar_moduleJNI.delete_java_wxmenubar(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public java_wxmenubar(int style) {
    this(wxmenubar_moduleJNI.new_java_wxmenubar(style), true);
  }

  public void java_Append(java_wxmenu menu, String name) {
    wxmenubar_moduleJNI.java_wxmenubar_java_Append(swigCPtr, this, java_wxmenu.getCPtr(menu), menu, name);
  }

}
