/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wx.JNI;

public class java_wxbutton {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected java_wxbutton(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(java_wxbutton obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        wxbutton_moduleJNI.delete_java_wxbutton(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    wxbutton_moduleJNI.java_wxbutton_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    wxbutton_moduleJNI.java_wxbutton_change_ownership(this, swigCPtr, true);
  }

  public java_wxbutton(java_wxpanel parent, int id, String title, int x, int y, int width, int height, int style, String name) {
    this(wxbutton_moduleJNI.new_java_wxbutton(java_wxpanel.getCPtr(parent), parent, id, title, x, y, width, height, style, name), true);
    wxbutton_moduleJNI.java_wxbutton_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void OnClick() {
    if (getClass() == java_wxbutton.class) wxbutton_moduleJNI.java_wxbutton_OnClick(swigCPtr, this); else wxbutton_moduleJNI.java_wxbutton_OnClickSwigExplicitjava_wxbutton(swigCPtr, this);
  }

  public void click_event_occured(SWIGTYPE_p_wxCommandEvent event) {
    wxbutton_moduleJNI.java_wxbutton_click_event_occured(swigCPtr, this, SWIGTYPE_p_wxCommandEvent.getCPtr(event));
  }

}
