/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wx.JNI;

public class wxapp_module {
  public static void java_wxEntryStart(int argc, String[] argv) {
    wxapp_moduleJNI.java_wxEntryStart(argc, argv);
  }

  public static void java_wxEntryCleanup() {
    wxapp_moduleJNI.java_wxEntryCleanup();
  }

}
