/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wx.JNI;

public class wxbutton_wxframe_moduleJNI {
  public final static native long new_java_wxbutton(long jarg1, java_wxframe jarg1_, int jarg2, String jarg3, int jarg4, int jarg5, int jarg6, int jarg7, int jarg8, String jarg9);
  public final static native void delete_java_wxbutton(long jarg1);
}
