/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wx.JNI;

public class wxbutton_moduleJNI {
  public final static native long new_java_wxframe(long jarg1, java_wxframe jarg1_, int jarg2, String jarg3, int jarg4, int jarg5, int jarg6, int jarg7, int jarg8, String jarg9);
  public final static native void java_wxframe_java_Show(long jarg1, java_wxframe jarg1_, boolean jarg2);
  public final static native void java_wxframe_java_Center__SWIG_0(long jarg1, java_wxframe jarg1_);
  public final static native void java_wxframe_java_Center__SWIG_1(long jarg1, java_wxframe jarg1_, int jarg2);
  public final static native void java_wxframe_java_SetMenuBar(long jarg1, java_wxframe jarg1_, long jarg2);
  public final static native void delete_java_wxframe(long jarg1);
  public final static native long new_java_wxpanel(long jarg1, java_wxframe jarg1_, int jarg2, int jarg3, int jarg4, int jarg5, int jarg6, int jarg7, String jarg8);
  public final static native void delete_java_wxpanel(long jarg1);
  public final static native long new_java_wxbutton(long jarg1, java_wxpanel jarg1_, int jarg2, String jarg3, int jarg4, int jarg5, int jarg6, int jarg7, int jarg8, String jarg9);
  public final static native void java_wxbutton_OnClick(long jarg1, java_wxbutton jarg1_);
  public final static native void java_wxbutton_OnClickSwigExplicitjava_wxbutton(long jarg1, java_wxbutton jarg1_);
  public final static native void java_wxbutton_click_event_occured(long jarg1, java_wxbutton jarg1_, long jarg2);
  public final static native void delete_java_wxbutton(long jarg1);
  public final static native void java_wxbutton_director_connect(java_wxbutton obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void java_wxbutton_change_ownership(java_wxbutton obj, long cptr, boolean take_or_release);

  public static void SwigDirector_java_wxbutton_OnClick(java_wxbutton self) {
    self.OnClick();
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
