/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wx.JNI;

public class wxdialog_moduleJNI {
  public final static native long new_java_wxdialog(long jarg1, java_wxpanel jarg1_, int jarg2, String jarg3, int jarg4, int jarg5, int jarg6, int jarg7, int jarg8, String jarg9);
  public final static native void java_wxdialog_java_ShowModal(long jarg1, java_wxdialog jarg1_);
  public final static native void java_wxdialog_java_Show(long jarg1, java_wxdialog jarg1_);
  public final static native void java_wxdialog_java_Center__SWIG_0(long jarg1, java_wxdialog jarg1_);
  public final static native void java_wxdialog_java_Center__SWIG_1(long jarg1, java_wxdialog jarg1_, int jarg2);
  public final static native void delete_java_wxdialog(long jarg1);
}
