/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package wx.JNI;

public class wxmenubar_moduleJNI {
  public final static native long new_java_wxmenubar(int jarg1);
  public final static native void java_wxmenubar_java_Append(long jarg1, java_wxmenubar jarg1_, long jarg2, java_wxmenu jarg2_, String jarg3);
  public final static native void delete_java_wxmenubar(long jarg1);
  public final static native long new_java_wxmenu__SWIG_0(int jarg1);
  public final static native long new_java_wxmenu__SWIG_1(String jarg1, int jarg2);
  public final static native void java_wxmenu_java_Append__SWIG_0(long jarg1, java_wxmenu jarg1_, int jarg2, String jarg3);
  public final static native void java_wxmenu_java_Append__SWIG_1(long jarg1, java_wxmenu jarg1_, long jarg2, java_wxmenuitem jarg2_);
  public final static native void java_wxmenu_java_Bind(long jarg1, java_wxmenu jarg1_, long jarg2, java_wxmenuitem jarg2_);
  public final static native void delete_java_wxmenu(long jarg1);
  public final static native long new_java_wxmenuitem(long jarg1, java_wxmenu jarg1_, int jarg2, String jarg3);
  public final static native void java_wxmenuitem_OnClick(long jarg1, java_wxmenuitem jarg1_);
  public final static native void java_wxmenuitem_OnClickSwigExplicitjava_wxmenuitem(long jarg1, java_wxmenuitem jarg1_);
  public final static native void java_wxmenuitem_click_event_occured(long jarg1, java_wxmenuitem jarg1_, long jarg2);
  public final static native void delete_java_wxmenuitem(long jarg1);
  public final static native void java_wxmenuitem_director_connect(java_wxmenuitem obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void java_wxmenuitem_change_ownership(java_wxmenuitem obj, long cptr, boolean take_or_release);

  public static void SwigDirector_java_wxmenuitem_OnClick(java_wxmenuitem self) {
    self.OnClick();
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
